name: Run C++

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '.github/workflows/runCPP.yml'
  push:
    branches:
      - main
    paths:
      - '**/*.cpp'
      - '.github/workflows/runCPP.yml'
  workflow_dispatch:
    inputs:
      executeSchemeOPSICA:
        description: 'SchemeOPSICA'
        required: true
        default: true
        type: boolean
      executeSchemeSPSICA:
        description: 'SchemeSPSICA'
        required: true
        default: true
        type: boolean
      executeSchemeVPSICA:
        description: 'SchemeVPSICA'
        required: true
        default: true
        type: boolean
      cppVersion:
        description: 'C++ version'
        required: true
        default: 23
        type: choice
        options:
          - 17
          - 20
          - 23
      outputFormat:
        description: 'Output format'
        required: true
        default: '.csv'
        type: choice
        options:
          - '.csv'
          - '.tsv'
          - '.txt'
      decimalPlace:
        description: 'Decimal place'
        required: true
        default: 9
        type: choice
        options:
          - 0
          - 's'
          - 'second'
          - 3
          - 'ms'
          - 'millisecond'
          - 6
          - 'microsecond'
          - 9
          - 'ns'
          - 'nanosecond'
          - 12
          - 'ps'
          - 'picosecond'
          - 15
          - 'fs'
          - 'femtosecond'
      runCount:
        description: 'Run count'
        required: true
        default: '10'
        type: string

permissions:
  contents: read

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
      decimalPlace: ${{ steps.decimalPlace.outputs.decimalPlace }}
      runCount: ${{ steps.runCount.outputs.runCount }}
      timeString: ${{ steps.timeString.outputs.timeString }}
    steps:
      - name: Prepare the matrix
        id: matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]];
          then
            executeSchemeOPSICA="${{ github.event.inputs.executeSchemeOPSICA }}"
            executeSchemeSPSICA="${{ github.event.inputs.executeSchemeSPSICA }}"
            executeSchemeVPSICA="${{ github.event.inputs.executeSchemeVPSICA }}"
          else
            executeSchemeOPSICA="true"
            executeSchemeSPSICA="true"
            executeSchemeVPSICA="true"
          fi
          matrix=()
          [[ "true" == "${executeSchemeOPSICA}" ]] && matrix+=("SchemeOPSICA/SchemeOPSICA.cpp" "SchemeVPSICA/SchemePSICA.cpp")
          [[ "true" == "${executeSchemeSPSICA}" ]] && matrix+=("SchemeSPSICA/SchemeSPSICA.cpp" "SchemeVPSICA/SchemePSICA.cpp")
          [[ "true" == "${executeSchemeVPSICA}" ]] && matrix+=("SchemeVPSICA/SchemePSICA.cpp" "SchemeVPSICA/SchemeVPSICAAlg2.cpp" "SchemeVPSICA/SchemeVPSICAAlg3.cpp" "SchemeVPSICA/SchemeVPSICAAlg4.cpp" "SchemeVPSICA/SchemeVPSICAAlg5.cpp")
          if [[ ${#matrix[@]} -ge 1 ]];
          then
            echo "matrix=$(printf '%s\n' "${matrix[@]}" | jq -R . | jq -s -c 'unique')" >> "${GITHUB_OUTPUT}"
          else
            echo "matrix=[]" >> "${GITHUB_OUTPUT}"
          fi
      
      - name: Prepare the decimal place
        id: decimalPlace
        run: |
          cd "${{ github.workspace }}"
          case "${decimalPlaceString}" in
            0|s|second)
              decimalPlace=0
              ;;
            3|ms|millisecond)
              decimalPlace=3
              ;;
            6|microsecond)
              decimalPlace=6
              ;;
            9|ns|nanosecond)
              decimalPlace=9
              ;;
            12|ps|picosecond)
              decimalPlace=12
              ;;
            15|fs|femtosecond)
              decimalPlace=15
              ;;
            *)
              decimalPlace=9
              ;;
          esac
          echo "decimalPlace=${decimalPlace}" >> "${GITHUB_OUTPUT}"
        env:
          decimalPlaceString: ${{ github.event.inputs.decimalPlace || '9' }}
      
      - name: Prepare the run count
        id: runCount
        run: |
          cd "${{ github.workspace }}"
          integerNumberString="$(echo -n "${runCountString}" | tr -cd '0-9A-Za-z+.-' | tr 'A-Z' 'a-z')"
          leadingSigns="${integerNumberString%%[!+-]*}"
          minusCount=$(echo -n "${leadingSigns}" | tr -cd '-' | wc -c)
          integerNumberString="${integerNumberString#$leadingSigns}"
          integerNumberString="$(echo "${integerNumberString}" | sed 's/^0*//')"
          radix=0
          case "${integerNumberString:0:1}" in
            'b')
              radix=2
              integerNumberString="${integerNumberString:1}"
              ;;
            'q')
              radix=4
              integerNumberString="${integerNumberString:1}"
              ;;
            'o')
              radix=8
              integerNumberString="${integerNumberString:1}"
              ;;
            'd')
              radix=10
              integerNumberString="${integerNumberString:1}"
              ;;
            'x')
              radix=16
              integerNumberString="${integerNumberString:1}"
              ;;
          esac
          if [[ 0 -eq ${radix} ]];
          then
            case "${integerNumberString: -1}" in
              'b')
                radix=2
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'q')
                radix=4
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'o')
                radix=8
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'd')
                radix=10
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'x')
                radix=16
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              *)
                radix=10
                ;;
            esac
          fi
          integerNumberString="$(echo "${integerNumberString}" | sed 's/^0*//')"
          integerNumberString="${integerNumberString%%.*}"
          runCount=0
          { runCount=$((${radix}#$integerNumberString)); } 2>/dev/null
          if (( minusCount % 2 == 1 ));
          then
            runCount=$(( -runCount ))
          fi
          if [[ ${runCount} -lt 1 ]];
          then
            runCount=10
          fi
          echo "runCount=${runCount}" >> "${GITHUB_OUTPUT}"
        env:
          runCountString: ${{ github.event.inputs.runCount || '10' }}
      
      - name: Prepare the time string
        id: timeString
        run: |
          cd "${{ github.workspace }}"
          timeString="HKT$(date '+%Y%m%d%H%M%S')"
          echo "timeString=${timeString}" >> "${GITHUB_OUTPUT}"
        env:
          TZ: 'Asia/Hong_Kong'
  
  runCPP:
    if: ${{ needs.prepare.outputs.matrix != '[]' }}
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cryptographicScheme: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          sparse-checkout: |
            ${{ matrix.cryptographicScheme }}
          persist-credentials: false
      
      - name: Get ready
        id: ready
        run: |
          cd "${{ github.workspace }}"
          directoryPath="$(dirname -- "${{ matrix.cryptographicScheme }}")"
          sourceFileName="$(basename -- "${{ matrix.cryptographicScheme }}")"
          mainFileName="${sourceFileName%.cpp}"
          sourceFilePath="${{ matrix.cryptographicScheme }}"
          binaryFilePath="${directoryPath}/${mainFileName}.bin"
          outputFilePath="${directoryPath}/${mainFileName}-C++${cppVersion}-p${decimalPlace}-r${runCount}-${timeString}${outputFormat}"
          outputFileName="$(basename -- "${outputFilePath}")"
          echo "Cryptographic scheme: ${{ matrix.cryptographicScheme }}"
          echo "C++ version: ${cppVersion}"
          echo "Decimal place: ${decimalPlaceString} (${decimalPlace})"
          echo "Run count: ${runCount}"
          echo "Time string: ${timeString}"
          echo "Output format: ${outputFormat}"
          echo "Output file path: ${outputFilePath}"
          echo "Output file name: ${outputFileName}"
          echo "sourceFilePath=${sourceFilePath}" >> "${GITHUB_OUTPUT}"
          echo "binaryFilePath=${binaryFilePath}" >> "${GITHUB_OUTPUT}"
          echo "outputFilePath=${outputFilePath}" >> "${GITHUB_OUTPUT}"
          echo "outputFileName=${outputFileName}" >> "${GITHUB_OUTPUT}"
        env:
          cppVersion: ${{ github.event.inputs.cppVersion || 23 }}
          decimalPlaceString: ${{ github.event.inputs.decimalPlace || '9' }}
          decimalPlace: ${{ needs.prepare.outputs.decimalPlace }}
          runCount: ${{ needs.prepare.outputs.runCount }}
          timeString: ${{ needs.prepare.outputs.timeString }}
          outputFormat: ${{ github.event.inputs.outputFormat || '.csv' }}
      
      - name: Compile the cryptographic scheme
        run: |
          cd "${{ github.workspace }}"
          g++ -std=c++${cppVersion} -Wall -Wextra -Wpedantic "${sourceFilePath}" -o "${binaryFilePath}"
        env:
          cppVersion: ${{ github.event.inputs.cppVersion || 23 }}
          sourceFilePath: ${{ steps.ready.outputs.sourceFilePath }}
          binaryFilePath: ${{ steps.ready.outputs.binaryFilePath }}
      
      - name: Run the cryptographic scheme
        run: |
          "${binaryFilePath}" -t 0 -h
          "${binaryFilePath}" -o "${outputFileName}" -p "${decimalPlace}" -r "${runCount}" -t 0 -y
        env:
          binaryFilePath: ${{ steps.ready.outputs.binaryFilePath }}
          outputFileName: ${{ steps.ready.outputs.outputFileName }}
          decimalPlace: ${{ needs.prepare.outputs.decimalPlace }}
          runCount: ${{ needs.prepare.outputs.runCount }}
      
      - name: Upload the result
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.outputFilePath }}
          archive: false
          if-no-files-found: error
