name: Run Java

on:
  pull_request:
    branches:
      - main
    paths:
      - '**/*.java'
      - '.github/workflows/runJava.yml'
  push:
    branches:
      - main
    paths:
      - '**/*.java'
      - '.github/workflows/runJava.yml'
  workflow_dispatch:
    inputs:
      executeSchemeAAIBME:
        description: 'SchemeAAIBME'
        required: true
        default: true
        type: boolean
      javaVersion:
        description: 'Java version'
        required: true
        default: 25
        type: choice
        options:
          - 11
          - 12
          - 13
          - 14
          - 15
          - 16
          - 17
          - 18
          - 19
          - 20
          - 21
          - 22
          - 23
          - 24
          - 25
          - 26
      outputFormat:
        description: 'Output format'
        required: true
        default: '.xlsx'
        type: choice
        options:
          - '.csv'
          - '.htm'
          - '.html'
          - '.json'
          - '.tex'
          - '.tsv'
          - '.txt'
          - '.xls'
          - '.xlsx'
          - '.xml'
          - '.yaml'
          - '.yml'
      decimalPlace:
        description: 'Decimal place'
        required: true
        default: 9
        type: choice
        options:
          - 0
          - 's'
          - 'second'
          - 3
          - 'ms'
          - 'millisecond'
          - 6
          - 'microsecond'
          - 9
          - 'ns'
          - 'nanosecond'
          - 12
          - 'ps'
          - 'picosecond'
          - 15
          - 'fs'
          - 'femtosecond'
      runCount:
        description: 'Run count'
        required: true
        default: '10'
        type: string

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    steps:
      - name: Prepare the matrix
        id: matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]];
          then
            executeSchemeAAIBME="${{ github.event.inputs.executeSchemeAAIBME }}"
          else
            executeSchemeAAIBME="true"
          fi
          matrix=()
          [[ "true" == "${executeSchemeAAIBME}" ]] && matrix+=("SchemeAAIBME/SchemeAAIBME.java")
          if [[ ${#matrix[@]} -ge 1 ]];
          then
            echo "matrix=$(printf '%s\n' "${matrix[@]}" | jq -R . | jq -s -c 'unique')" >> "${GITHUB_OUTPUT}"
          else
            echo "matrix=[]" >> "${GITHUB_OUTPUT}"
          fi
  
  runJava:
    if: needs.prepare.outputs.matrix != '[]'
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cryptographicScheme: ${{ fromJson(needs.prepare.outputs.matrix) }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            ${{ matrix.cryptographicScheme }}
            lib/
      
      - name: Get ready
        id: ready
        run: |
          cd "${{ github.workspace }}"
          
          # Decimal place #
          if [[ "s" == "${decimalPlaceString}" || "second" == "${decimalPlaceString}" ]];
          then
            decimalPlace=0
          elif [[ "ms" == "${decimalPlaceString}" || "millisecond" == "${decimalPlaceString}" ]];
          then
            decimalPlace=3
          elif [[ "microsecond" == "${decimalPlaceString}" ]];
          then
            decimalPlace=6
          elif [[ "ns" == "${decimalPlaceString}" || "nanosecond" == "${decimalPlaceString}" ]];
          then
            decimalPlace=9
          elif [[ "ps" == "${decimalPlaceString}" || "picosecond" == "${decimalPlaceString}" ]];
          then
            decimalPlace=12
          elif [[ "fs" == "${decimalPlaceString}" || "femtosecond" == "${decimalPlaceString}" ]];
          then
            decimalPlace=15
          else
            decimalPlace=${decimalPlaceString}
          fi
          
          # Run count #
          integerNumberString="$(echo -n "${runCountString}" | tr -cd '0-9A-Za-z+.-' | tr 'A-Z' 'a-z')"
          leadingSigns="${integerNumberString%%[!+-]*}"
          minusCount=$(echo -n "${leadingSigns}" | tr -cd '-' | wc -c)
          integerNumberString="${integerNumberString#$leadingSigns}"
          if [[ "${integerNumberString:0:1}" =~ [0-9] ]];
          then
            case "${integerNumberString: -1}" in
              'b')
                radix=2
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'q')
                radix=4
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'o')
                radix=8
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'd')
                radix=10
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              'x')
                radix=16
                integerNumberString="${integerNumberString:0:-1}"
                ;;
              *)
                radix=10
                ;;
            esac
          else
            case "${integerNumberString:0:1}" in
              'b')
                radix=2
                integerNumberString="${integerNumberString:1}"
                ;;
              'q')
                radix=4
                integerNumberString="${integerNumberString:1}"
                ;;
              'o')
                radix=8
                integerNumberString="${integerNumberString:1}"
                ;;
              'd')
                radix=10
                integerNumberString="${integerNumberString:1}"
                ;;
              'x')
                radix=16
                integerNumberString="${integerNumberString:1}"
                ;;
              *)
                radix=10
                ;;
            esac
          fi
          integerNumberString="$(echo "${integerNumberString}" | sed 's/^0*//')"
          integerNumberString="${integerNumberString%%.*}"
          runCount=10
          { runCount=$((${radix}#$integerNumberString)); } 2>/dev/null
          if (( minusCount % 2 == 1 ));
          then
            runCount=$(( -runCount ))
          fi
          if [[ ${runCount} -lt 1 ]];
          then
            runCount=10
          fi
          
          directoryPath="$(dirname "${{ matrix.cryptographicScheme }}")"
          mainFileName="$(basename "${{ matrix.cryptographicScheme }}" | sed "s/\.[^.]*\$//g")"
          timeString="HKT$(date '+%Y%m%d%H%M%S')"
          outputFilePath="${directoryPath}/${mainFileName}-Java${javaVersion}-p${decimalPlace}-r${runCount}-${timeString}${outputFormat}"
          outputFileName="$(basename "${outputFilePath}")"
          schemeLaTeXFilePath="${directoryPath}/${mainFileName}LaTeX/${mainFileName}-${timeString}.tex"
          schemePDFFilePath="${directoryPath}/${mainFileName}LaTeX/${mainFileName}-${timeString}.pdf"
          echo "Cryptographic scheme: ${{ matrix.cryptographicScheme }}"
          echo "Java version: ${javaVersion}"
          echo "Decimal place: ${decimalPlaceString} (${decimalPlace})"
          echo "Run count: ${runCountString} (${runCount})"
          echo "Time string: ${timeString}"
          echo "Output format: ${outputFormat}"
          echo "Output file path: ${outputFilePath}"
          echo "Output file name: ${outputFileName}"
          echo "Scheme LaTeX file path: ${schemeLaTeXFilePath}"
          echo "Scheme PDF file path: ${schemePDFFilePath}"
          echo "javaVersion=${javaVersion}" >> "${GITHUB_OUTPUT}"
          echo "decimalPlace=${decimalPlaceString}" >> "${GITHUB_OUTPUT}"
          echo "runCount=${runCount}" >> "${GITHUB_OUTPUT}"
          echo "timeString=${timeString}" >> "${GITHUB_OUTPUT}"
          echo "outputFilePath=${outputFilePath}" >> "${GITHUB_OUTPUT}"
          echo "outputFileName=${outputFileName}" >> "${GITHUB_OUTPUT}"
          echo "schemeLaTeXFilePath=${schemeLaTeXFilePath}" >> "${GITHUB_OUTPUT}"
          echo "schemePDFFilePath=${schemePDFFilePath}" >> "${GITHUB_OUTPUT}"
        env:
          javaVersion: ${{ github.event.inputs.javaVersion || 25 }}
          decimalPlaceString: ${{ github.event.inputs.decimalPlace || '9' }}
          runCountString: ${{ github.event.inputs.runCount || '10' }}
          TZ: 'Asia/Hong_Kong'
          outputFormat: ${{ github.event.inputs.outputFormat || '.xlsx' }}
      
      - name: Set up JDK ${{ steps.ready.outputs.javaVersion }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ steps.ready.outputs.javaVersion }}
          distribution: 'temurin'
      
      - name: Run the cryptographic scheme
        run: |
          cd "${{ github.workspace }}"
          echo "The current working directory is \"$(pwd)\". "
          if [[ -f "${{ matrix.cryptographicScheme }}" ]];
          then
            echo "\$ java -cp lib/jpbc-api-2.0.0.jar:lib/jpbc-plaf-2.0.0.jar \"${{ matrix.cryptographicScheme }}\" -o \"${{ steps.ready.outputs.outputFileName }}\" -p ${{ steps.ready.outputs.decimalPlace }} -r ${{ steps.ready.outputs.runCount }}"
            java -cp lib/jpbc-api-2.0.0.jar:lib/jpbc-plaf-2.0.0.jar "${{ matrix.cryptographicScheme }}" -o "${{ steps.ready.outputs.outputFileName }}" -p ${{ steps.ready.outputs.decimalPlace }} -r ${{ steps.ready.outputs.runCount }}
          else
            echo "Could not execute the cryptographic scheme file \"${{ matrix.cryptographicScheme }}\" via Java. "
            tree
          fi
      
      - name: Upload result
        uses: actions/upload-artifact@v7
        with:
          path: ${{ github.workspace }}/${{ steps.ready.outputs.outputFilePath }}
          archive: false
          if-no-files-found: error