name: Run Python

on:
  workflow_dispatch:
    inputs:
      outputFormat:
        description: 'Output format'
        required: true
        default: '.xlsx'
        type: choice
        options:
          - .csv
          - .html
          - .json
          - .tex
          - .tsv
          - .txt
          - .xls
          - .xlsx
          - .xml
          - .yaml
          - .yml
      pythonVersion:
        description: 'Python version'
        required: true
        default: '3.x'
        type: choice
        options:
          - '3.x'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
      runCount:
        description: 'Run count'
        required: true
        default: 10
        type: number
      decimalPlace:
        description: 'Decimal Place'
        required: true
        default: '9'
        type: choice
        options:
          - 0
          - s
          - second
          - 3
          - ms
          - millisecond
          - 6
          - microsecond
          - 9
          - ns
          - nanosecond
          - 12
          - ps
          - picosecond
          - 15
          - fs
          - femtosecond
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  runPython:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cryptographyScheme:
          - 'SchemeAAIBME/SchemeAAIBME.py'
          - 'SchemeAAIBME/SchemeFuzzyME.py'
          - 'SchemeCANIFPPCT/SchemeCANIFPPCT.py'
          - 'SchemeHIBME/SchemeAnonymousME.py'
          - 'SchemeHIBME/SchemeHIBME.py'
          - 'SchemeIBMEMR/SchemeIBBME.py'
          - 'SchemeIBMEMR/SchemeIBMEMR.py'
          - 'SchemeIBMETR/SchemeAIBE.py'
          - 'SchemeIBMETR/SchemeARES.py'
          - 'SchemeIBMETR/SchemeIBME.py'
          - 'SchemeIBMETR/SchemeIBMECH.py'
          - 'SchemeIBMETR/SchemeIBMETR.py'
          - 'SchemeIBPRME/SchemeIBPME.py'
          - 'SchemeIBPRME/SchemeIBPRME.py'
          - 'SchemeIBPRME/SchemePBAC.py'
          - 'SchemeVLPSICA/SchemeVLPSICA.py'
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ github.event.inputs.pythonVersion }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ github.event.inputs.pythonVersion }}
    
    - name: Install system dependencies
      run: |
        cd "${{ github.workspace }}"
        sudo apt-get update
        sudo apt-get install -y bison build-essential flex libfl-dev libgmp-dev libssl-dev wget
    
    - name: Build and install the PBC library
      run: |
        cd "${{ github.workspace }}"
        wget https://crypto.stanford.edu/pbc/files/pbc-1.0.0.tar.gz
        tar -xzf pbc-1.0.0.tar.gz
        cd pbc-1.0.0
        ./configure LDFLAGS="-lgmp"
        make -j$(nproc)
        sudo make install
        sudo ldconfig
    
    - name: Build and install the Python charm library
      run: |
        cd "${{ github.workspace }}"
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        git clone https://github.com/JHUISI/charm.git
        cd charm
        chmod +x ./configure.sh
        ./configure.sh
        make -j$(nproc)
        sudo make install
    
    - name: Get ready to run
      id: ready
      run: |
        cd "${{ github.workspace }}"
        echo "Cryptography scheme: ${{ matrix.cryptographyScheme }}"
        echo "Output format: ${outputFormat}"
        echo "Python version: ${pythonVersion}"
        echo "Run count: ${runCount}"
        echo "Decimal place: ${decimalPlace}"
        outputFilePath="$(echo "${{ matrix.cryptographyScheme }}" | sed "s/\.[^.]*\$/-Python${pythonVersion}-r${runCount}-HKT$(date '+%Y%m%d%H%M%S')${outputFormat}/g")"
        echo "outputFilePath=${outputFilePath}" >> ${GITHUB_OUTPUT}
        echo "outputFileName=$(basename "${outputFilePath}")" >> ${GITHUB_OUTPUT}
        echo "pythonVersion=${pythonVersion}" >> ${GITHUB_OUTPUT}
        echo "runCount=${runCount}" >> ${GITHUB_OUTPUT}
        if [[ "s" == "${decimalPlace}" || "second" == "${decimalPlace}" ]];
        then
          echo "decimalPlace=0" >> ${GITHUB_OUTPUT}
        elif [[ "ms" == "${decimalPlace}" || "millisecond" == "${decimalPlace}" ]];
        then
          echo "decimalPlace=3" >> ${GITHUB_OUTPUT}
        elif [[ "microsecond" == "${decimalPlace}" ]];
        then
          echo "decimalPlace=6" >> ${GITHUB_OUTPUT}
        elif [[ "ns" == "${decimalPlace}" || "nanosecond" == "${decimalPlace}" ]];
        then
          echo "decimalPlace=9" >> ${GITHUB_OUTPUT}
        elif [[ "ps" == "${decimalPlace}" || "picosecond" == "${decimalPlace}" ]];
        then
          echo "decimalPlace=12" >> ${GITHUB_OUTPUT}
        elif [[ "fs" == "${decimalPlace}" || "femtosecond" == "${decimalPlace}" ]];
        then
          echo "decimalPlace=15" >> ${GITHUB_OUTPUT}
        else
          echo "decimalPlace=${decimalPlace}" >> ${GITHUB_OUTPUT}
        fi
      env:
        outputFormat: ${{ github.event.inputs.outputFormat || '.xlsx' }}
        pythonVersion: ${{ github.event.inputs.pythonVersion || '3.x' }}
        runCount: ${{ github.event.inputs.runCount || 10 }}
        decimalPlace: ${{ github.event.inputs.decimalPlace || '9' }}
        TZ: 'Asia/Hong_Kong'
    
    - name: Run the cryptography scheme
      run: |
        cd "${{ github.workspace }}"
        echo "The current working directory is \"$(pwd)\". "
        if [[ -f "${{ matrix.cryptographyScheme }}" ]];
        then
          echo "\$ python \"${{ matrix.cryptographyScheme }}\" -o \"${{ steps.ready.outputs.outputFileName }}\" -r ${{ steps.ready.outputs.runCount }} -p ${{ steps.ready.outputs.decimalPlace }} -t 0 -y"
          python "${{ matrix.cryptographyScheme }}" -o "${{ steps.ready.outputs.outputFileName }}" -r ${{ steps.ready.outputs.runCount }} -p ${{ steps.ready.outputs.decimalPlace }} -t 0 y
        else
          echo "Could not execute the cryptography scheme file \"${{ matrix.cryptographyScheme }}\" via Python ${{ steps.ready.outputs.pythonVersion }}. "
          tree
        fi
    
    - name: Upload results
      uses: actions/upload-artifact@v4
      with:
        name: ${{ steps.ready.outputs.outputFileName }}
        path: ${{ github.workspace }}/${{ steps.ready.outputs.outputFilePath }}
        if-no-files-found: error