name: Run Python

# Thanks to [https://github.com/JHUISI/charm/blob/dev/.github/workflows/ci.yml](https://github.com/JHUISI/charm/blob/dev/.github/workflows/ci.yml). 

on:
  workflow_dispatch:
    inputs:
      runSchemeAAIBME:
        description: 'SchemeAAIBME'
        required: false
        default: false
        type: boolean
      runSchemeCANIFPPCT:
        description: 'SchemeCANIFPPCT'
        required: false
        default: false
        type: boolean
      runSchemeHIBME:
        description: 'SchemeHIBME'
        required: false
        default: true
        type: boolean
      runSchemeIBMEMR:
        description: 'SchemeIBMEMR'
        required: false
        default: true
        type: boolean
      runSchemeIBMETR:
        description: 'SchemeIBMETR'
        required: false
        default: true
        type: boolean
      runSchemeIBPRME:
        description: 'SchemeIBPRME'
        required: false
        default: true
        type: boolean
      runSchemeVLPSICA:
        description: 'SchemeVLPSICA'
        required: false
        default: false
        type: boolean
      outputFormat:
        description: 'Output format'
        required: true
        default: '.xlsx'
        type: choice
        options:
          - .csv
          - .htm
          - .html
          - .json
          - .tex
          - .tsv
          - .txt
          - .xls
          - .xlsx
          - .xml
          - .yaml
          - .yml
      pythonVersion:
        description: 'Python version'
        required: true
        default: '3.x'
        type: choice
        options:
          - '3.x'
          - '3.10'
          - '3.11'
          - '3.12'
          - '3.13'
          - '3.14'
      runCount:
        description: 'Run count'
        required: true
        default: 10
        type: number
      decimalPlace:
        description: 'Decimal Place'
        required: true
        default: '9'
        type: choice
        options:
          - 0
          - s
          - second
          - 3
          - ms
          - millisecond
          - 6
          - microsecond
          - 9
          - ns
          - nanosecond
          - 12
          - ps
          - picosecond
          - 15
          - fs
          - femtosecond
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.matrix.outputs.matrix }}
    
    steps:
      - name: Prepare the matrix
        id: matrix
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]];
          then
            runSchemeAAIBME="${{ github.event.inputs.runSchemeAAIBME }}"
            runSchemeCANIFPPCT="${{ github.event.inputs.runSchemeCANIFPPCT }}"
            runSchemeHIBME="${{ github.event.inputs.runSchemeHIBME }}"
            runSchemeIBMEMR="${{ github.event.inputs.runSchemeIBMEMR }}"
            runSchemeIBMETR="${{ github.event.inputs.runSchemeIBMETR }}"
            runSchemeIBPRME="${{ github.event.inputs.runSchemeIBPRME }}"
            runSchemeVLPSICA="${{ github.event.inputs.runSchemeVLPSICA }}"
          else
            runSchemeAAIBME="false"
            runSchemeCANIFPPCT="false"
            runSchemeHIBME="true"
            runSchemeIBMEMR="true"
            runSchemeIBMETR="true"
            runSchemeIBPRME="true"
            runSchemeVLPSICA="false"
          fi
          matrix=()
          if [[ "true" == "${runSchemeAAIBME}" ]];
          then
            matrix+=("SchemeAAIBME/SchemeAAIBME.py" "SchemeAAIBME/SchemeFuzzyME.py" "SchemeIBMETR/SchemeIBMECH.py")
          fi
          if [[ "true" == "${runSchemeCANIFPPCT}" ]];
          then
            matrix+=("SchemeCANIFPPCT/SchemeCANIFPPCT.py")
          fi
          if [[ "true" == "${runSchemeHIBME}" ]];
          then
            matrix+=("SchemeHIBME/SchemeAnonymousME.py" "SchemeHIBME/SchemeHIBME.py")
          fi
          if [[ "true" == "${runSchemeIBMEMR}" ]];
          then
            matrix+=("SchemeIBMEMR/SchemeIBBME.py" "SchemeIBMETR/SchemeIBME.py" "SchemeIBMEMR/SchemeIBMEMR.py")
          fi
          if [[ "true" == "${runSchemeIBMETR}" ]];
          then
            matrix+=("SchemeIBMETR/SchemeAIBE.py" "SchemeIBMETR/SchemeARES.py" "SchemeIBMETR/SchemeIBME.py" "SchemeIBMETR/SchemeIBMECH.py" "SchemeIBMETR/SchemeIBMETR.py")
          fi
          if [[ "true" == "${runSchemeIBPRME}" ]];
          then
            matrix+=("SchemeIBMETR/SchemeIBME.py" "SchemeIBMETR/SchemeIBMECH.py" "SchemeIBPRME/SchemeIBPME.py" "SchemeIBPRME/SchemeIBPRME.py" "SchemeIBPRME/SchemePBAC.py")
          fi
          if [[ "true" == "${runSchemeVLPSICA}" ]];
          then
            matrix+=("SchemeVLPSICA/SchemeVLPSICA.py")
          fi
          if [[ ${#matrix[@]} -ge 1 ]];
          then
            echo "matrix=$(printf '%s\n' "${matrix[@]}" | jq -R . | jq -s -c 'unique')" >> "${GITHUB_OUTPUT}"
          else
            echo "matrix=[]" >> "${GITHUB_OUTPUT}"
          fi
  
  runPython:
    if: needs.prepare.outputs.matrix != '[]'
    needs: prepare
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cryptographicScheme: ${{ fromJson(needs.prepare.outputs.matrix) }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v6
    
    - name: Get ready
      id: ready
      run: |
        cd "${{ github.workspace }}"
        if [[ "s" == "${decimalPlaceString}" || "second" == "${decimalPlaceString}" ]];
        then
          decimalPlace=0
        elif [[ "ms" == "${decimalPlaceString}" || "millisecond" == "${decimalPlaceString}" ]];
        then
          decimalPlace=3
        elif [[ "microsecond" == "${decimalPlaceString}" ]];
        then
          decimalPlace=6
        elif [[ "ns" == "${decimalPlaceString}" || "nanosecond" == "${decimalPlaceString}" ]];
        then
          decimalPlace=9
        elif [[ "ps" == "${decimalPlaceString}" || "picosecond" == "${decimalPlaceString}" ]];
        then
          decimalPlace=12
        elif [[ "fs" == "${decimalPlaceString}" || "femtosecond" == "${decimalPlaceString}" ]];
        then
          decimalPlace=15
        else
          decimalPlace=${decimalPlaceString}
        fi
        outputFilePath="$(echo "${{ matrix.cryptographicScheme }}" | sed "s/\.[^.]*\$/-Python${pythonVersion}-r${runCount}-p${decimalPlace}-HKT$(date '+%Y%m%d%H%M%S')${outputFormat}/g")"
        outputFileName="$(basename "${outputFilePath}")"
        echo "Cryptographic scheme: ${{ matrix.cryptographicScheme }}"
        echo "Output format: ${outputFormat}"
        echo "Output file path: ${outputFilePath}"
        echo "Output file name: ${outputFileName}"
        echo "Python version: ${pythonVersion}"
        echo "Run count: ${runCount}"
        echo "Decimal place: ${decimalPlaceString} (${decimalPlace})"
        echo "outputFilePath=${outputFilePath}" >> "${GITHUB_OUTPUT}"
        echo "outputFileName=${outputFileName}" >> "${GITHUB_OUTPUT}"
        echo "pythonVersion=${pythonVersion}" >> "${GITHUB_OUTPUT}"
        echo "runCount=${runCount}" >> "${GITHUB_OUTPUT}"
        echo "decimalPlace=${decimalPlaceString}" >> "${GITHUB_OUTPUT}"
      env:
        outputFormat: ${{ github.event.inputs.outputFormat || '.xlsx' }}
        pythonVersion: ${{ github.event.inputs.pythonVersion || '3.x' }}
        runCount: ${{ github.event.inputs.runCount || 10 }}
        decimalPlaceString: ${{ github.event.inputs.decimalPlace || '9' }}
        TZ: 'Asia/Hong_Kong'
    
    - name: Set up Python ${{ steps.ready.outputs.pythonVersion }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ steps.ready.outputs.pythonVersion }}
    
    - name: Install system dependencies
      run: |
        cd "${{ github.workspace }}"
        sudo apt-get update
        sudo apt-get install -y build-essential flex libfl-dev libgmp-dev libssl-dev wget
    
    - name: Build and install the PBC library
      run: |
        cd "${{ github.workspace }}"
        wget https://crypto.stanford.edu/pbc/files/pbc-1.0.0.tar.gz
        tar -xzf pbc-1.0.0.tar.gz
        cd pbc-1.0.0
        ./configure LDFLAGS="-lgmp"
        make -j$(nproc)
        sudo make install
        sudo ldconfig
    
    - name: Build and install the Python charm library
      run: |
        cd "${{ github.workspace }}"
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        git clone https://github.com/JHUISI/charm.git
        cd charm
        chmod +x ./configure.sh
        ./configure.sh
        make -j$(nproc)
        sudo make install
    
    - name: Run the cryptographic scheme
      run: |
        cd "${{ github.workspace }}"
        echo "The current working directory is \"$(pwd)\". "
        if [[ -f "${{ matrix.cryptographicScheme }}" ]];
        then
          echo "\$ python \"${{ matrix.cryptographicScheme }}\" -h"
          python "${{ matrix.cryptographicScheme }}" -h
          echo ""
          echo "\$ python \"${{ matrix.cryptographicScheme }}\" -o \"${{ steps.ready.outputs.outputFileName }}\" -r ${{ steps.ready.outputs.runCount }} -p ${{ steps.ready.outputs.decimalPlace }} -t 0 -y"
          python "${{ matrix.cryptographicScheme }}" -o "${{ steps.ready.outputs.outputFileName }}" -r ${{ steps.ready.outputs.runCount }} -p ${{ steps.ready.outputs.decimalPlace }} -t 0 y
        else
          echo "Could not execute the cryptographic scheme file \"${{ matrix.cryptographicScheme }}\" via Python ${{ steps.ready.outputs.pythonVersion }}. "
          tree
        fi
    
    - name: Upload the result
      uses: actions/upload-artifact@v7
      with:
        path: ${{ github.workspace }}/${{ steps.ready.outputs.outputFilePath }}
        archive: false
        if-no-files-found: error